"""added FK

Revision ID: 24798896d525
Revises: f41244eb6802
Create Date: 2024-04-25 23:24:34.654442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24798896d525'
down_revision = 'f41244eb6802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_service', schema=None) as batch_op:
        batch_op.drop_constraint('department_service_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('department_service_ibfk_1', 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###
